name: origamicore
version: 0.0.8
description: origami core framework
homepage: https://github.com/vahidHossaini/origamicore
environment:
  sdk: '>=2.10.0 <3.0.0'
  
dev_dependencies:
  pedantic: ^1.9.0 